### ISSUE TITLE
Feature Request: Upload from filesystem

### ISSUE THREAD

**Issue by digitalman2112** [nim901/gfycat#1]
gfycat supports uploading a file from the filesystem by first uploading to their amazon s3 bucket with a key, then calling transcode with that key. Please consider adding to gfycatuploader, thanks!

Additional details here:
http://www.gfycat.com/api
and
http://www.reddit.com/r/gfycat/comments/22zswi/file_upload_using_the_api/

**Comment by nim901** [comment]
I've added this.
Thank you :)
