### ISSUE TITLE
Same name for module and class

### ISSUE THREAD

**Issue by boeckhoff** [nim901/gfycat#6]
When I import the module as usual using ipython2.7 on linux I get the following error:

`import gfycat`
`gfycat.gfycat()`

`AttributeError: 'module' object has no attribute 'gfycat'`

I think this is because python confuses the module namespace with the class namespace.
[might be relevant](http://stackoverflow.com/questions/2393544/python-classname-same-as-file-module-name-leads-to-inheritance-issue)

The solution for me was

`from gfycat import gfycat`
`g = gfycat`
`upload = g.gfycat()`

Am I doing something wrong here? Because this should clearly not be the way to access a module.
Shouldn't this class be renamed to avoid any confusion by python or the people using it?

**Comment by boeckhoff** [comment]
@jtara1 has renamed the class the in his/her [fork](https://github.com/jtara1/gfycat) but it still doesn't work for me

**Comment by jtara1** [comment]
Try `from gfycat.gfycat import gfycat` where the last gfycat is the name of the class.

Or just `import gfycat.gfycat`

**Comment by boeckhoff** [comment]
ok thanks, this might be kind of confusing still but I will close the issue.
